apply from: 'gradle/scripts/helpers.gradle'

repositories {
    // Other repositories described by default:
    // CleanroomMC: https://maven.cleanroommc.com
    maven {
        name 'CurseMaven'
        url 'https://curse.cleanroommc.com'
    }
    maven {
        name 'Modrinth'
        url 'https://api.modrinth.com/maven'
    }
    maven {
        name 'BlameJared'
        url 'https://maven.blamejared.com'
    }
    mavenLocal() // Must be last for caching to work
}

dependencies {
    compileOnly "com.cleanroommc:sponge-mixin:0.20.10+mixin.0.8.7"
    if (propertyBool('enable_lwjglx')) {
        compileOnly "com.cleanroommc:lwjglx:1.0.0"
    }

    runtimeOnly  'mezz:jei:4.29.2'
    modImplementation 'com.blamejared:MTLib:3.0.5.15'
    modImplementation 'CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-4.1.20.705'
    modImplementation 'curse.maven:Botania-225643:3330934'
    modImplementation 'curse.maven:extended-crafting-nomifactory-edition-398267:5778512'
    modImplementation 'curse.maven:cucumber-272335:2645867'
    modRuntimeOnly 'curse.maven:ModTweaker-220954:3840577'
    modRuntimeOnly 'curse.maven:botania-tweaks-295114:3092102'
}
